apiVersion: apps/v1
kind: Deployment
metadata:
    name: dp-airflow
spec:
    replicas: 1
    selector:
        matchLabels:
            app: airflow
    template:
        metadata:
            labels:
                app: airflow
        spec:
            volumes:
            - name: pv-airflow
              persistentVolumeClaim:
               claimName: pvc-airflow
            containers:
            - name: airflow
              image: ferrettivinicius/airflow-aula-fia:latest
              ports:
              - containerPort: 8081
              volumeMounts:
                - mountPath: /usr/share/airflow
                  name: pv-airflow
