apiVersion: v1
kind: Pod
metadata:
  name: pod-postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:14
      ports:
        - containerPort: 5432