apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow
  labels:
    type: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/c/Airflow