apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
      requests:
          storage: 1Gi
  selector:
      matchLabels:
          type: airflow