
apiVersion: v1
kind: Service
metadata:
  name: svc-node-port-minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      nodePort: 30001  #range entre 30000 e 32767
      port: 9090
  type: NodePort