apiVersion: v1
kind: Service
metadata:
  name: svc-node-spark
spec:
  selector:
    app: nginx
  ports:
    - name: http
      nodePort: 30000 #range entre 30000 e 32767
      port: 80
  type: NodePort