apiVersion: v1
kind: Service
metadata:
  name: svc-node-port-nifi
spec:
  selector:
    app: nifi
  ports:
    - name: http
      nodePort: 30002 #range entre 30000 e 32767
      port: 80
  type: NodePort