apiVersion: v1
kind: Pod
metadata:
  name: pod-spark
  labels:
    app: spark
spec:
  containers:
    - name: spark-master
      image: mjhea0/spark-hadoop:3.2.0
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 7077